export const currencies = [
    { code: 'AED', country: 'United Arab Emirates Dirham' },
    { code: 'AFN', country: 'Afghan Afghani' },
    { code: 'ALL', country: 'Albanian Lek' },
    { code: 'AMD', country: 'Armenian Dram' },
    { code: 'ANG', country: 'Netherlands Antillean Guilder' },
    { code: 'AOA', country: 'Angolan Kwanza' },
    { code: 'ARS', country: 'Argentine Peso' },
    { code: 'AUD', country: 'Australian Dollar' },
    { code: 'AWG', country: 'Aruban Florin' },
    { code: 'AZN', country: 'Azerbaijani Manat' },
    { code: 'BAM', country: 'Bosnia-Herzegovina Convertible Mark' },
    { code: 'BBD', country: 'Barbadian Dollar' },
    { code: 'BDT', country: 'Bangladeshi Taka' },
    { code: 'BGN', country: 'Bulgarian Lev' },
    { code: 'BHD', country: 'Bahraini Dinar' },
    { code: 'BIF', country: 'Burundian Franc' },
    { code: 'BMD', country: 'Bermudan Dollar' },
    { code: 'BND', country: 'Brunei Dollar' },
    { code: 'BOB', country: 'Bolivian Boliviano' },
    { code: 'BRL', country: 'Brazilian Real' },
    { code: 'BSD', country: 'Bahamian Dollar' },
    { code: 'BTC', country: 'Bitcoin' },
    { code: 'BTN', country: 'Bhutanese Ngultrum' },
    { code: 'BWP', country: 'Botswanan Pula' },
    { code: 'BYN', country: 'Belarusian Ruble' },
    { code: 'BZD', country: 'Belize Dollar' },
    { code: 'CAD', country: 'Canadian Dollar' },
    { code: 'CDF', country: 'Congolese Franc' },
    { code: 'CHF', country: 'Swiss Franc' },
    { code: 'CLF', country: 'Chilean Unit of Account (UF)' },
    { code: 'CLP', country: 'Chilean Peso' },
    { code: 'CNH', country: 'Chinese Yuan (Offshore)' },
    { code: 'CNY', country: 'Chinese Yuan' },
    { code: 'COP', country: 'Colombian Peso' },
    { code: 'CRC', country: 'Costa Rican Colón' },
    { code: 'CUC', country: 'Cuban Convertible Peso' },
    { code: 'CUP', country: 'Cuban Peso' },
    { code: 'CVE', country: 'Cape Verdean Escudo' },
    { code: 'CZK', country: 'Czech Republic Koruna' },
    { code: 'DJF', country: 'Djiboutian Franc' },
    { code: 'DKK', country: 'Danish Krone' },
    { code: 'DOP', country: 'Dominican Peso' },
    { code: 'DZD', country: 'Algerian Dinar' },
    { code: 'EGP', country: 'Egyptian Pound' },
    { code: 'ERN', country: 'Eritrean Nakfa' },
    { code: 'ETB', country: 'Ethiopian Birr' },
    { code: 'EUR', country: 'Euro' },
    { code: 'FJD', country: 'Fijian Dollar' },
    { code: 'FKP', country: 'Falkland Islands Pound' },
    { code: 'GBP', country: 'British Pound Sterling' },
    { code: 'GEL', country: 'Georgian Lari' },
    { code: 'GGP', country: 'Guernsey Pound' },
    { code: 'GHS', country: 'Ghanaian Cedi' },
    { code: 'GIP', country: 'Gibraltar Pound' },
    { code: 'GMD', country: 'Gambian Dalasi' },
    { code: 'GNF', country: 'Guinean Franc' },
    { code: 'GTQ', country: 'Guatemalan Quetzal' },
    { code: 'GYD', country: 'Guyanaese Dollar' },
    { code: 'HKD', country: 'Hong Kong Dollar' },
    { code: 'HNL', country: 'Honduran Lempira' },
    { code: 'HRK', country: 'Croatian Kuna' },
    { code: 'HTG', country: 'Haitian Gourde' },
    { code: 'HUF', country: 'Hungarian Forint' },
    { code: 'IDR', country: 'Indonesian Rupiah' },
    { code: 'ILS', country: 'Israeli New Sheqel' },
    { code: 'IMP', country: 'Manx pound' },
    { code: 'INR', country: 'Indian Rupee' },
    { code: 'IQD', country: 'Iraqi Dinar' },
    { code: 'IRR', country: 'Iranian Rial' },
    { code: 'ISK', country: 'Icelandic Króna' },
    { code: 'JEP', country: 'Jersey Pound' },
    { code: 'JMD', country: 'Jamaican Dollar' },
    { code: 'JOD', country: 'Jordanian Dinar' },
    { code: 'JPY', country: 'Japanese Yen' },
    { code: 'KES', country: 'Kenyan Shilling' },
    { code: 'KGS', country: 'Kyrgystani Som' },
    { code: 'KHR', country: 'Cambodian Riel' },
    { code: 'KMF', country: 'Comorian Franc' },
    { code: 'KPW', country: 'North Korean Won' },
    { code: 'KRW', country: 'South Korean Won' },
    { code: 'KWD', country: 'Kuwaiti Dinar' },
    { code: 'KYD', country: 'Cayman Islands Dollar' },
    { code: 'KZT', country: 'Kazakhstani Tenge' },
    { code: 'LAK', country: 'Laotian Kip' },
    { code: 'LBP', country: 'Lebanese Pound' },
    { code: 'LKR', country: 'Sri Lankan Rupee' },
    { code: 'LRD', country: 'Liberian Dollar' },
    { code: 'LSL', country: 'Lesotho Loti' },
    { code: 'LYD', country: 'Libyan Dinar' },
    { code: 'MAD', country: 'Moroccan Dirham' },
    { code: 'MDL', country: 'Moldovan Leu' },
    { code: 'MGA', country: 'Malagasy Ariary' },
    { code: 'MKD', country: 'Macedonian Denar' },
    { code: 'MMK', country: 'Myanma Kyat' },
    { code: 'MNT', country: 'Mongolian Tugrik' },
    { code: 'MOP', country: 'Macanese Pataca' },
    { code: 'MRU', country: 'Mauritanian Ouguiya' },
    { code: 'MUR', country: 'Mauritian Rupee' },
    { code: 'MVR', country: 'Maldivian Rufiyaa' },
    { code: 'MWK', country: 'Malawian Kwacha' },
    { code: 'MXN', country: 'Mexican Peso' },
    { code: 'MYR', country: 'Malaysian Ringgit' },
    { code: 'MZN', country: 'Mozambican Metical' },
    { code: 'NAD', country: 'Namibian Dollar' },
    { code: 'NGN', country: 'Nigerian Naira' },
    { code: 'NIO', country: 'Nicaraguan Córdoba' },
    { code: 'NOK', country: 'Norwegian Krone' },
    { code: 'NPR', country: 'Nepalese Rupee' },
    { code: 'NZD', country: 'New Zealand Dollar' },
    { code: 'OMR', country: 'Omani Rial' },
    { code: 'PAB', country: 'Panamanian Balboa' },
    { code: 'PEN', country: 'Peruvian Nuevo Sol' },
    { code: 'PGK', country: 'Papua New Guinean Kina' },
    { code: 'PHP', country: 'Philippine Peso' },
    { code: 'PKR', country: 'Pakistani Rupee' },
    { code: 'PLN', country: 'Polish Zloty' },
    { code: 'PYG', country: 'Paraguayan Guarani' },
    { code: 'QAR', country: 'Qatari Rial' },
    { code: 'RON', country: 'Romanian Leu' },
    { code: 'RSD', country: 'Serbian Dinar' },
    { code: 'RUB', country: 'Russian Ruble' },
    { code: 'RWF', country: 'Rwandan Franc' },
    { code: 'SAR', country: 'Saudi Riyal' },
    { code: 'SBD', country: 'Solomon Islands Dollar' },
    { code: 'SCR', country: 'Seychellois Rupee' },
    { code: 'SDG', country: 'Sudanese Pound' },
    { code: 'SEK', country: 'Swedish Krona' },
    { code: 'SGD', country: 'Singapore Dollar' },
    { code: 'SHP', country: 'Saint Helena Pound' },
    { code: 'SLL', country: 'Sierra Leonean Leone' },
    { code: 'SOS', country: 'Somali Shilling' },
    { code: 'SRD', country: 'Surinamese Dollar' },
    { code: 'SSP', country: 'South Sudanese Pound' },
    { code: 'STD', country: 'São Tomé and Príncipe Dobra (pre-2018)' },
    { code: 'STN', country: 'São Tomé and Príncipe Dobra' },
    { code: 'SVC', country: 'Salvadoran Colón' },
    { code: 'SYP', country: 'Syrian Pound' },
    { code: 'SZL', country: 'Swazi Lilangeni' },
    { code: 'THB', country: 'Thai Baht' },
    { code: 'TJS', country: 'Tajikistani Somoni' },
    { code: 'TMT', country: 'Turkmenistani Manat' },
    { code: 'TND', country: 'Tunisian Dinar' },
    { code: 'TOP', country: "Tongan Pa'anga" },
    { code: 'TRY', country: 'Turkish Lira' },
    { code: 'TTD', country: 'Trinidad and Tobago Dollar' },
    { code: 'TWD', country: 'New Taiwan Dollar' },
    { code: 'TZS', country: 'Tanzanian Shilling' },
    { code: 'UAH', country: 'Ukrainian Hryvnia' },
    { code: 'UGX', country: 'Ugandan Shilling' },
    { code: 'USD', country: 'United States Dollar' },
    { code: 'UYU', country: 'Uruguayan Peso' },
    { code: 'UZS', country: 'Uzbekistan Som' },
    { code: 'VEF', country: 'Venezuelan Bolívar Fuerte (Old)' },
    { code: 'VES', country: 'Venezuelan Bolívar Soberano' },
    { code: 'VND', country: 'Vietnamese Dong' },
    { code: 'VUV', country: 'Vanuatu Vatu' },
    { code: 'WST', country: 'Samoan Tala' },
    { code: 'XAF', country: 'CFA Franc BEAC' },
    { code: 'XAG', country: 'Silver Ounce' },
    { code: 'XAU', country: 'Gold Ounce' },
    { code: 'XCD', country: 'East Caribbean Dollar' },
    { code: 'XDR', country: 'Special Drawing Rights' },
    { code: 'XOF', country: 'CFA Franc BCEAO' },
    { code: 'XPD', country: 'Palladium Ounce' },
    { code: 'XPF', country: 'CFP Franc' },
    { code: 'XPT', country: 'Platinum Ounce' },
    { code: 'YER', country: 'Yemeni Rial' },
    { code: 'ZAR', country: 'South African Rand' },
    { code: 'ZMW', country: 'Zambian Kwacha' },
    { code: 'ZWL', country: 'Zimbabwean Dollar' },
];
